package com.safevault.app.data.crypto

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyPermanentlyInvalidatedException
import android.security.keystore.KeyProperties
import android.security.keystore.UserNotAuthenticatedException
import com.safevault.app.domain.model.AutoLockTimeout
import com.safevault.app.util.VaultLockManager
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * AES-256-GCM encryption backed by a non-exportable, auth-bound key in the
 * Android Keystore.
 *
 * Security properties:
 *  - The 256-bit key is generated inside the Keystore and can never be read
 *    out of the process; only encrypt/decrypt operations are permitted.
 *  - The key is **bound to user authentication**: the Keystore itself refuses
 *    to run a cipher unless the user authenticated with a class-3 biometric or
 *    the device credential within [AUTH_VALIDITY_SECONDS]. Biometrics are an
 *    OS-enforced gate here, not merely a UI gate.
 *  - GCM provides confidentiality *and* integrity (authentication tag), so any
 *    tampering with stored ciphertext is detected on decryption.
 *  - A fresh 12-byte IV is generated by the provider for every encryption and
 *    stored alongside the ciphertext (IV reuse under GCM would be catastrophic,
 *    so we never supply our own IV on encrypt).
 *  - StrongBox (a dedicated secure element) is requested on supported hardware
 *    with a graceful fallback to the TEE-backed Keystore.
 *
 * A validity window is used instead of per-operation authentication
 * (`setUserAuthenticationParameters(0, ...)`): a per-operation binding requires
 * a `BiometricPrompt` + `CryptoObject` round trip for *every* `Cipher`, i.e.
 * one prompt per note on every list render. The trade-off is documented in the
 * README — a time-bound key is bound to the secure lock screen (removing or
 * resetting it invalidates the key) but is not invalidated by merely enrolling
 * an additional fingerprint.
 */
@Singleton
class KeystoreCryptoManager @Inject constructor(
    private val lockManager: VaultLockManager,
) : CryptoManager {

    override fun encrypt(plaintext: String): EncryptedPayload = runCrypto("Encryption") {
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        }
        EncryptedPayload(
            iv = cipher.iv,
            ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8)),
        )
    }

    override fun decrypt(payload: EncryptedPayload): String = runCrypto("Decryption") {
        val spec = GCMParameterSpec(GCM_TAG_LENGTH_BITS, payload.iv)
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.DECRYPT_MODE, getOrCreateKey(), spec)
        }
        String(cipher.doFinal(payload.ciphertext), Charsets.UTF_8)
    }

    /**
     * Maps Keystore failures onto [CryptoFailure] so callers can tell a single
     * unreadable record apart from a session-wide authentication problem.
     */
    private inline fun <T> runCrypto(operation: String, block: () -> T): T = try {
        block()
    } catch (e: UserNotAuthenticatedException) {
        // The authenticated window elapsed: drop back to the lock screen, which
        // re-presents BiometricPrompt and refreshes the Keystore auth token.
        lockManager.lock()
        throw CryptoException(
            CryptoFailure.AUTH_REQUIRED,
            "$operation requires a fresh authentication",
            e,
        )
    } catch (e: KeyPermanentlyInvalidatedException) {
        // The secure lock screen was removed/reset. Everything written with the
        // old key is unrecoverable; drop the dead alias so a fresh key can be
        // created and the vault stays usable, then warn on the lock screen.
        deleteKey()
        lockManager.onKeyInvalidated()
        throw CryptoException(
            CryptoFailure.KEY_INVALIDATED,
            "$operation failed: the vault key was invalidated by the OS",
            e,
        )
    } catch (e: Exception) {
        throw CryptoException(CryptoFailure.UNREADABLE, "$operation failed", e)
    }

    private fun getOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let {
            return it.secretKey
        }
        return generateKey()
    }

    private fun deleteKey() {
        runCatching {
            KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }.deleteEntry(KEY_ALIAS)
        }
    }

    private fun generateKey(): SecretKey {
        val generator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            ANDROID_KEYSTORE,
        )

        val builder = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_SIZE_BITS)
            .setRandomizedEncryptionRequired(true)
            .setUserAuthenticationRequired(true)

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            builder.setUserAuthenticationParameters(
                AUTH_VALIDITY_SECONDS,
                KeyProperties.AUTH_BIOMETRIC_STRONG or KeyProperties.AUTH_DEVICE_CREDENTIAL,
            )
        } else {
            // minSdk 26: pre-API-30 equivalent of the call above.
            @Suppress("DEPRECATION")
            builder.setUserAuthenticationValidityDurationSeconds(AUTH_VALIDITY_SECONDS)
        }

        // Prefer StrongBox on hardware that provides it; silently fall back if not.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            builder.setIsStrongBoxBacked(true)
        }

        return try {
            generator.init(builder.build())
            generator.generateKey()
        } catch (e: Exception) {
            // StrongBox unavailable on this device -> retry without it.
            generator.init(
                builder.setIsStrongBoxBackedCompat(false).build(),
            )
            generator.generateKey()
        }
    }

    /** Small helper so the fallback path reads cleanly across API levels. */
    private fun KeyGenParameterSpec.Builder.setIsStrongBoxBackedCompat(
        enabled: Boolean,
    ): KeyGenParameterSpec.Builder = apply {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            setIsStrongBoxBacked(enabled)
        }
    }

    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val KEY_ALIAS = "safevault_master_key"
        private const val KEY_SIZE_BITS = 256
        private const val GCM_TAG_LENGTH_BITS = 128
        private const val TRANSFORMATION =
            "${KeyProperties.KEY_ALGORITHM_AES}/" +
                "${KeyProperties.BLOCK_MODE_GCM}/" +
                KeyProperties.ENCRYPTION_PADDING_NONE

        /**
         * How long the Keystore keeps accepting a previous authentication. Kept
         * equal to the longest auto-lock the user can pick, so the OS window is
         * never shorter than a legitimately unlocked session.
         */
        private val AUTH_VALIDITY_SECONDS =
            (AutoLockTimeout.entries.maxOf { it.millis } / 1_000L).toInt()
    }
}
